#Powerful quotes & sayings about life

quotes_teletips = [
"Love For All, Hatred For None.Boss @Loltage", 
"Change the world by being yourself.Boss @Loltage",
"Every moment is a fresh beginning.Boss @Loltage",
"Never regret anything that made you smile.Boss @Loltage",
"Die with memories, not dreams.Boss @Loltage",
"Aspire to inspire before we expire.Boss @Loltage",
"Everything you can imagine is real.Boss @Loltage",
"Simplicity is the ultimate sophistication.Boss @Loltage",
"Whatever you do, do it well.Boss @Loltage",
"What we think, we become.Boss @Loltage",
"All limitations are self-imposed.Boss @Loltage",
"Tough times never last but tough people do.Boss @Loltage",
"Problems are not stop signs, they are guidelines.Boss @Loltage",
"Havecourage to start and enough heart to finish.Boss @Loltage",
"I could agree with you but then we’d both be wrong.Boss @Loltage",
"the things you can find, if you don’t stay behind.Boss @Loltage",
"Determine your priorities and focus on them.Boss @Loltage",
"Be so good they can’t ignore you.Boss @Loltage",
"Yesterday you said tomorrow. Just do it.Boss @Loltage",
"Don't need it to be easy, I need it to be worth it.Boss @Loltage",
"Never let your emotions overpower your intelligence.Boss @Loltage",
"forever but at least we got these memories.Boss @Loltage",
"Don’t you know your imperfections is a blessing?Boss @Loltage",
"Reality is wrong, dreams are for real.Boss @Loltage",
"To live will be an awfully big adventure.Boss @Loltage",
"Try to be a rainbow in someone’s cloud.Boss @Loltage",
"There is no substitute for hard work.Boss @Loltage",
"What consumes your mind controls your life.Boss @Loltage",
"Strive for greatness.Boss @Loltage",
"And still, I rise.Boss @Loltage",
"The time is always right to do what is right.Boss @Loltage",
"Let the beauty of what you love be what you do.Boss @Loltage",
"May choices reflect your hopes, not your fears.Boss @Loltage",
"A happy soul is the best shield for a cruel world.Boss @Loltage",
"not always light and black is not always dark.Boss @Loltage",
"Happiness depends upon ourselves.Boss @Loltage",
"Turn your wounds into wisdom.Boss @Loltage",
"Change the game, don’t let the game change you.Boss @Loltage",
"It hurt because it mattered.Boss @Loltage",
"I will remember and recover, not forgive and forget.Boss @Loltage",
"The meaning of life is to give life meaning.Boss @Loltage",
"When words fail, music speaks.Boss @Loltage",
"Embrace the glorious mess that you are.Boss @Loltage",
"I have nothing to lose but something to gain.Boss @Loltage"
]
